openapi: 3.0.0
info:
  title: Supabase Auth API
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v0

paths:
  /test:
    get:
      summary: Test route
      responses:
        '200':
          description: Test success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string