openapi: 3.0.3
info:
  title: Foodie OpenAPI
  version: 1.0.0

servers:
  - url: http://localhost:4000/api/v0

paths:
  /categories:
    get:
      summary: Get a category by ID
      responses:
        '200':
          description: Found category
          content:
            application/json:
              schema:
                type: object
                properties:
                  category:
                    type: string
        '400':
          description: Category not found
  /categories/items/{categoryId}:
    get:
      summary: Get items by categoryId
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Found items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: string
        '404':
          description: Category not found